# Generated by Django 5.1.5 on 2025-03-02 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_nombre', models.TextField(max_length=100)),
                ('producto_precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto_imagen', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
            ],
            options={
                'ordering': ['-producto_nombre'],
            },
        ),
    ]
