# Generated by Django 5.1.5 on 2025-03-04 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['producto_nombre']},
        ),
    ]
