# Generated by Django 5.1.5 on 2025-03-05 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0002_alter_producto_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['producto_nombre'], 'permissions': [('puede_administrar_productos', 'Puede administrar productos')]},
        ),
    ]
