# Generated by Django 5.1.5 on 2025-03-06 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='nombre_producto',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='precio_total',
        ),
    ]
