# Generated by Django 5.1.5 on 2025-03-06 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0002_remove_compra_nombre_producto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='precio_producto',
        ),
    ]
